"""Tests for the dependency-anchor pre-flight check (#557).

Unit tests exercising the script's functions directly, with mocked PyPI
responses.  Synthetic requirement files and diffs prove the failure lanes
without touching the network.

Each test pins one acceptance criterion.  The criterion number appears in
the test name so the evidence body can trace each checkbox to its test.
AC8 is pinned by a mutation receipt generated by ``scripts/mutation_receipt.py``
(see ``docs/assurance/anchor-pin-mutation-receipt.md``), not by a test in
this file: a test that monkeypatches the function it claims to mutate leaves
the shipped file unchanged, so it proves nothing about the shipped check.
"""

from __future__ import annotations

import importlib.util
import re
import subprocess
import sys
import textwrap
from pathlib import Path
from types import ModuleType
from unittest.mock import patch

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]
_CI_YML = _REPO_ROOT / ".github" / "workflows" / "ci.yml"

# Import functions directly so mocks apply in-process.
# scripts/ carries no __init__.py and is not a package, so load by path.
_spec = importlib.util.spec_from_file_location(
    "check_dependency_anchor",
    _REPO_ROOT / "scripts" / "check_dependency_anchor.py",
)
assert _spec is not None and _spec.loader is not None
_mod: ModuleType = importlib.util.module_from_spec(_spec)
sys.modules[_spec.name] = _mod
_spec.loader.exec_module(_mod)

NetworkError = _mod.NetworkError
check_exact_pin_constraint = _mod.check_exact_pin_constraint
collect_anchor_metadata = _mod.collect_anchor_metadata
main = _mod.main
parse_diff = _mod.parse_diff
parse_pyproject_requirements = _mod.parse_pyproject_requirements
parse_requirement = _mod.parse_requirement
parse_requirements_file = _mod.parse_requirements_file

# Real pydantic metadata shape, per the #549 ticket: pydantic latest pins
# pydantic-core with ==2.46.5, which is what requirements-ci.txt already pins.
_PYDANTIC_REQUIRES_DIST_2_46_5 = [
    "pydantic-core==2.46.5",
    "typing-extensions>=4.12.0",
    "annotated-types>=0.6.0",
]


def _pydantic_metadata(requires_dist: list[str]) -> dict[str, object]:
    return {"info": {"requires_dist": list(requires_dist)}}


# ---------------------------------------------------------------------------
# Pure-function unit tests (no network, no I/O)
# ---------------------------------------------------------------------------


class TestParseRequirement:
    """parse_requirement returns (canonical_name, version) or None."""

    def test_exact_pin(self) -> None:
        assert parse_requirement("pydantic-core==2.46.5") == ("pydantic_core", "2.46.5")

    def test_greater_equal(self) -> None:
        assert parse_requirement("click>=8.5.0") == ("click", "8.5.0")

    def test_comment_line(self) -> None:
        assert parse_requirement("# a comment") is None

    def test_empty_line(self) -> None:
        assert parse_requirement("") is None

    def test_bare_name(self) -> None:
        assert parse_requirement("pydantic") is None

    def test_hyphen_to_underscore(self) -> None:
        assert parse_requirement("pydantic-core==1.0.0") == ("pydantic_core", "1.0.0")

    def test_option_line_is_skipped(self) -> None:
        assert parse_requirement("-c constraints.txt") is None


class TestParseDiff:
    """parse_diff extracts changed packages with old and new versions."""

    def test_simple_bump(self) -> None:
        diff = textwrap.dedent("""\
            --- a/requirements-ci.txt
            +++ b/requirements-ci.txt
            @@ -1,2 +1,2 @@
            -pydantic-core==2.46.5
            +pydantic-core==2.48.0
        """)
        changes = parse_diff(diff)
        assert "pydantic_core" in changes
        old, new = changes["pydantic_core"]
        assert old == "2.46.5"
        assert new == "2.48.0"

    def test_no_changes(self) -> None:
        diff = textwrap.dedent("""\
            --- a/requirements-ci.txt
            +++ b/requirements-ci.txt
        """)
        assert parse_diff(diff) == {}

    def test_unchanged_line_is_dropped(self) -> None:
        diff = textwrap.dedent("""\
            --- a/requirements-ci.txt
            +++ b/requirements-ci.txt
            @@ -1,2 +1,2 @@
            -pydantic-core==2.46.5
            +pydantic-core==2.46.5
        """)
        assert parse_diff(diff) == {}


class TestCheckExactPinConstraint:
    """check_exact_pin_constraint returns the blocking == pin or None.

    The check is exact-pin only.  A non-== specifier (range or lower bound)
    is out of scope and never blocks: the dependabot group coordinates ranges,
    and the defect this check exists for is the == anchor with nothing new to
    bump to.
    """

    def test_exact_pin_blocks_above(self) -> None:
        requires_dist = ["pydantic-core==2.46.5"]
        pin = check_exact_pin_constraint(requires_dist, "pydantic-core", "2.48.0")
        assert pin == "==2.46.5"

    def test_exact_pin_passes_at_same_version(self) -> None:
        requires_dist = ["pydantic-core==2.46.5"]
        pin = check_exact_pin_constraint(requires_dist, "pydantic-core", "2.46.5")
        assert pin is None

    def test_exact_pin_passes_below_the_pin(self) -> None:
        # The defect is a follower bumped ABOVE an == anchor; a proposed below
        # the pin is not the dependabot bump-up shape, so it is not refused.
        requires_dist = ["pydantic-core==2.49.0"]
        pin = check_exact_pin_constraint(requires_dist, "pydantic-core", "2.48.0")
        assert pin is None

    def test_non_exact_specifier_is_ignored(self) -> None:
        requires_dist = ["pydantic-core>=2.46.5,<2.47.0"]
        pin = check_exact_pin_constraint(requires_dist, "pydantic-core", "2.48.0")
        assert pin is None

    def test_no_requires_dist(self) -> None:
        pin = check_exact_pin_constraint(None, "pydantic-core", "2.48.0")
        assert pin is None

    def test_different_package_ignored(self) -> None:
        requires_dist = ["other-package==1.0.0"]
        pin = check_exact_pin_constraint(requires_dist, "pydantic-core", "2.48.0")
        assert pin is None

    def test_marker_stripped_before_pin_read(self) -> None:
        requires_dist = ['pydantic-core==2.46.5; python_version >= "3.12"']
        pin = check_exact_pin_constraint(requires_dist, "pydantic-core", "2.48.0")
        assert pin == "==2.46.5"


class TestParseRequirementsFile:
    """parse_requirements_file returns {canonical_name: version}."""

    def test_basic(self, tmp_path: Path) -> None:
        req = tmp_path / "requirements.txt"
        req.write_text(
            textwrap.dedent("""\
                pydantic==2.13.5
                pydantic-core==2.46.5
            """),
            encoding="utf-8",
        )
        result = parse_requirements_file(req)
        assert result == {"pydantic": "2.13.5", "pydantic_core": "2.46.5"}


class TestParsePyprojectRequirements:
    """parse_pyproject_requirements extracts [project.dependencies]."""

    def test_basic(self, tmp_path: Path) -> None:
        pyproject = tmp_path / "pyproject.toml"
        pyproject.write_text(
            textwrap.dedent("""\
                [project]
                name = "test"
                dependencies = [
                    "pydantic>=2.6",
                    "click>=8.5.0",
                ]
            """),
            encoding="utf-8",
        )
        result = parse_pyproject_requirements(pyproject)
        assert result == {"pydantic": "2.6", "click": "8.5.0"}


# ---------------------------------------------------------------------------
# AC1: the check runs before the test matrix and fails the run early
# ---------------------------------------------------------------------------


class TestRunsBeforeTheMatrix:
    """AC1: an isolated gate completes before the test matrix starts.

    Reads the real ci.yml and asserts that the matrix `test` job needs the
    dedicated anchor-check job. A same-job step runs too late: a conflicting
    requirements-ci.txt change fails in each matrix cell's Install step before
    that step can execute.
    """

    def test_matrix_needs_the_pre_flight_gate(self) -> None:
        text = _CI_YML.read_text(encoding="utf-8")
        gate_match = re.search(
            r"\n  dependency-anchor:\n(?P<body>.*?)(?=\n  [A-Za-z_-]+:\n)", text, re.DOTALL
        )
        assert gate_match is not None, "could not find the `dependency-anchor` job in ci.yml"
        gate = gate_match.group("body")
        assert "Pre-flight dependency anchor check" in gate
        assert "requirements-ci.txt" in gate

        job_match = re.search(r"\n  test:\n(?P<body>.*?)(?=\n  [A-Za-z_-]+:\n)", text, re.DOTALL)
        assert job_match is not None, "could not find the `test:` job in ci.yml"
        job = job_match.group("body")
        assert re.search(r"^    needs: dependency-anchor$", job, re.MULTILINE), (
            "the test matrix must wait for the pre-flight anchor-check job; a same-job "
            "step runs after the constrained install that #549 breaks"
        )


# ---------------------------------------------------------------------------
# AC2: refuses a follower bump above an exact-pinned anchor's requirement
# ---------------------------------------------------------------------------


class TestRefusesBumpAboveExactPin:
    """AC2: pydantic-core 2.46.5 -> 2.48.0 refused by pydantic's ==2.46.5 pin.

    Reproduces the 2026-08-17 shape.  The refusal message names the anchor
    (pydantic), the pin (==2.46.5) and the proposed version (2.48.0).
    """

    def test_refuses(self, tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
        req = tmp_path / "requirements-ci.txt"
        req.write_text(
            textwrap.dedent("""\
                pydantic==2.13.5
                pydantic-core==2.46.5
            """),
            encoding="utf-8",
        )
        diff = tmp_path / "changes.diff"
        diff.write_text(
            textwrap.dedent("""\
                --- a/requirements-ci.txt
                +++ b/requirements-ci.txt
                @@ -1,2 +1,2 @@
                -pydantic-core==2.46.5
                +pydantic-core==2.48.0
            """),
            encoding="utf-8",
        )

        with patch(
            "check_dependency_anchor.fetch_pypi_metadata",
            side_effect=lambda pkg, _version: (
                _pydantic_metadata(_PYDANTIC_REQUIRES_DIST_2_46_5) if pkg == "pydantic" else {}
            ),
        ):
            result = main(["--requirements", str(req), "--diff", str(diff)])

        assert result == 1
        err = capsys.readouterr().err
        assert "pydantic" in err
        assert "==2.46.5" in err
        assert "2.48.0" in err
        assert "No published anchor satisfies" in err


# ---------------------------------------------------------------------------
# AC7: red demonstration reproduces #549 as a fixture
# ---------------------------------------------------------------------------


class TestReproducesIssue549:
    """AC7: the exact #549 scenario — pydantic-core 2.46.5 -> 2.49.0 refused.

    This is the named fixture the mutation receipt (AC8) kills: under a
    mutant that disables the exact-pin comparison, this test turns red.
    """

    def test_reproduces(self, tmp_path: Path) -> None:
        req = tmp_path / "requirements-ci.txt"
        req.write_text(
            textwrap.dedent("""\
                pydantic==2.13.5
                pydantic-core==2.46.5
            """),
            encoding="utf-8",
        )
        diff = tmp_path / "changes.diff"
        diff.write_text(
            textwrap.dedent("""\
                --- a/requirements-ci.txt
                +++ b/requirements-ci.txt
                @@ -1,2 +1,2 @@
                -pydantic-core==2.46.5
                +pydantic-core==2.49.0
            """),
            encoding="utf-8",
        )

        with patch(
            "check_dependency_anchor.fetch_pypi_metadata",
            side_effect=lambda pkg, _version: (
                _pydantic_metadata(_PYDANTIC_REQUIRES_DIST_2_46_5) if pkg == "pydantic" else {}
            ),
        ):
            result = main(["--requirements", str(req), "--diff", str(diff)])

        assert result == 1


# ---------------------------------------------------------------------------
# AC3: passes a bump where the anchor's pin permits the new version
# ---------------------------------------------------------------------------


class TestPassesCoordinatedBump:
    """AC3: a coordinated bump the anchor's == pin permits is not refused.

    A newer pydantic (2.14.0) pins pydantic-core==2.49.0; the dependabot
    pydantic-stack group coordinates both bumps together, so the proposed
    pydantic-core (2.49.0) sits at the anchor's == pin and pip resolves it.
    """

    def test_passes(self, tmp_path: Path) -> None:
        req = tmp_path / "requirements-ci.txt"
        req.write_text(
            textwrap.dedent("""\
                pydantic==2.14.0
                pydantic-core==2.49.0
            """),
            encoding="utf-8",
        )
        diff = tmp_path / "changes.diff"
        diff.write_text(
            textwrap.dedent("""\
                --- a/requirements-ci.txt
                +++ b/requirements-ci.txt
                @@ -1,2 +1,2 @@
                -pydantic==2.13.5
                +pydantic==2.14.0
                -pydantic-core==2.46.5
                +pydantic-core==2.49.0
            """),
            encoding="utf-8",
        )

        pydantic_2140 = _pydantic_metadata(["pydantic-core==2.49.0", "typing-extensions>=4.12.0"])

        with patch(
            "check_dependency_anchor.fetch_pypi_metadata",
            side_effect=lambda pkg, _version: pydantic_2140 if pkg == "pydantic" else {},
        ):
            result = main(["--requirements", str(req), "--diff", str(diff)])

        assert result == 0


# ---------------------------------------------------------------------------
# AC4: passes a bump of a package no anchor pins with ==
# ---------------------------------------------------------------------------


class TestPassesUnpinnedPackage:
    """AC4: bumping a package no anchor pins with == passes."""

    def test_passes(self, tmp_path: Path) -> None:
        req = tmp_path / "requirements-ci.txt"
        req.write_text(
            textwrap.dedent("""\
                click==8.5.0
                pydantic==2.13.5
            """),
            encoding="utf-8",
        )
        diff = tmp_path / "changes.diff"
        diff.write_text(
            textwrap.dedent("""\
                --- a/requirements-ci.txt
                +++ b/requirements-ci.txt
                @@ -1,2 +1,2 @@
                -click==8.5.0
                +click==8.6.0
            """),
            encoding="utf-8",
        )

        with patch(
            "check_dependency_anchor.fetch_pypi_metadata",
            return_value=_pydantic_metadata([]),
        ):
            result = main(["--requirements", str(req), "--diff", str(diff)])

        assert result == 0


# ---------------------------------------------------------------------------
# AC5: discovers the anchor relationship from published metadata
# ---------------------------------------------------------------------------


class TestDiscoversAnchorFromMetadata:
    """AC5: the check reads PyPI metadata rather than using a hand-maintained list.

    Uses a fictitious anchor that pins the changed package with ==, so no
    hardcoded list of known pairs could supply the relationship.
    """

    def test_discovers(self, tmp_path: Path) -> None:
        req = tmp_path / "requirements-ci.txt"
        req.write_text(
            textwrap.dedent("""\
                fictitious-anchor==1.0.0
                fictitious-follower==1.0.0
            """),
            encoding="utf-8",
        )
        diff = tmp_path / "changes.diff"
        diff.write_text(
            textwrap.dedent("""\
                --- a/requirements-ci.txt
                +++ b/requirements-ci.txt
                @@ -1,2 +1,2 @@
                -fictitious-follower==1.0.0
                +fictitious-follower==2.0.0
            """),
            encoding="utf-8",
        )

        anchor_metadata = _pydantic_metadata(["fictitious-follower==1.0.0"])

        with patch(
            "check_dependency_anchor.fetch_pypi_metadata",
            side_effect=lambda pkg, _version: anchor_metadata if pkg == "fictitious_anchor" else {},
        ):
            result = main(["--requirements", str(req), "--diff", str(diff)])

        assert result == 1

    def test_collect_caches_each_anchor_once(self) -> None:
        """AC5 / robustness: each candidate anchor is read once, not per pair."""
        calls: list[str] = []

        def _record(pkg: str, version: str) -> dict[str, object]:
            calls.append(f"{pkg}=={version}")
            return _pydantic_metadata([])

        with patch("check_dependency_anchor.fetch_pypi_metadata", side_effect=_record):
            collect_anchor_metadata({"a": "1", "b": "2", "c": "3"})
        assert sorted(calls) == ["a==1", "b==2", "c==3"]

    def test_uses_the_anchor_version_declared_in_constraints(self, tmp_path: Path) -> None:
        """A newer anchor release cannot stand in for the declared anchor."""
        req = tmp_path / "requirements-ci.txt"
        req.write_text(
            textwrap.dedent("""\
                pydantic==2.13.5
                pydantic-core==2.46.5
            """),
            encoding="utf-8",
        )
        diff = tmp_path / "changes.diff"
        diff.write_text(
            textwrap.dedent("""\
                --- a/requirements-ci.txt
                +++ b/requirements-ci.txt
                @@ -1,2 +1,2 @@
                -pydantic-core==2.46.5
                +pydantic-core==2.49.0
            """),
            encoding="utf-8",
        )

        def _metadata(package: str, version: str) -> dict[str, object]:
            if (package, version) == ("pydantic", "2.13.5"):
                return _pydantic_metadata(["pydantic-core==2.46.5"])
            if (package, version) == ("pydantic", "2.14.0"):
                return _pydantic_metadata(["pydantic-core==2.49.0"])
            return {}

        with patch("check_dependency_anchor.fetch_pypi_metadata", side_effect=_metadata):
            result = main(["--requirements", str(req), "--diff", str(diff)])

        assert result == 1


# ---------------------------------------------------------------------------
# AC6: network failure reaching the index is a refusal with a distinct message
# ---------------------------------------------------------------------------


class TestNetworkFailureIsRefusal:
    """AC6: a network error reaching PyPI is a refusal, never a pass."""

    def test_refuses_with_distinct_message(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        req = tmp_path / "requirements-ci.txt"
        req.write_text(
            textwrap.dedent("""\
                pydantic==2.13.5
                pydantic-core==2.46.5
            """),
            encoding="utf-8",
        )
        diff = tmp_path / "changes.diff"
        diff.write_text(
            textwrap.dedent("""\
                --- a/requirements-ci.txt
                +++ b/requirements-ci.txt
                @@ -1,2 +1,2 @@
                -pydantic-core==2.46.5
                +pydantic-core==2.48.0
            """),
            encoding="utf-8",
        )

        with patch(
            "check_dependency_anchor.fetch_pypi_metadata",
            side_effect=NetworkError(
                "network error fetching https://pypi.org/pypi/pydantic/json: timeout"
            ),
        ):
            result = main(["--requirements", str(req), "--diff", str(diff)])

        assert result == 1
        err = capsys.readouterr().err
        assert "network error reaching the index" in err


# ---------------------------------------------------------------------------
# Additional edge cases
# ---------------------------------------------------------------------------


class TestEdgeCases:
    """Edge cases and error paths."""

    def test_no_changes_in_diff(self, tmp_path: Path) -> None:
        """An empty diff passes with no network calls."""
        req = tmp_path / "requirements-ci.txt"
        req.write_text("pydantic-core==2.46.5\n", encoding="utf-8")
        diff = tmp_path / "changes.diff"
        diff.write_text(
            textwrap.dedent("""\
                --- a/requirements-ci.txt
                +++ b/requirements-ci.txt
            """),
            encoding="utf-8",
        )

        result = main(["--requirements", str(req), "--diff", str(diff)])
        assert result == 0

    def test_missing_requirements_file(self, tmp_path: Path) -> None:
        """Missing requirements file is a refusal."""
        diff = tmp_path / "changes.diff"
        diff.write_text(
            textwrap.dedent("""\
                --- a/requirements-ci.txt
                +++ b/requirements-ci.txt
                @@ -1 +1 @@
                -pydantic-core==2.46.5
                +pydantic-core==2.48.0
            """),
            encoding="utf-8",
        )

        result = main(["--requirements", str(tmp_path / "nonexistent.txt"), "--diff", str(diff)])
        assert result == 1

    def test_missing_diff_file(self, tmp_path: Path) -> None:
        """Missing diff file is a refusal."""
        req = tmp_path / "requirements-ci.txt"
        req.write_text("pydantic-core==2.46.5\n", encoding="utf-8")

        result = main(["--requirements", str(req), "--diff", str(tmp_path / "nonexistent.diff")])
        assert result == 1

    def test_anchor_with_no_requires_dist(self, tmp_path: Path) -> None:
        """An anchor whose requires_dist is None does not cause a refusal."""
        req = tmp_path / "requirements-ci.txt"
        req.write_text(
            textwrap.dedent("""\
                some-package==1.0.0
                pydantic-core==2.46.5
            """),
            encoding="utf-8",
        )
        diff = tmp_path / "changes.diff"
        diff.write_text(
            textwrap.dedent("""\
                --- a/requirements-ci.txt
                +++ b/requirements-ci.txt
                @@ -1,2 +1,2 @@
                -pydantic-core==2.46.5
                +pydantic-core==2.48.0
            """),
            encoding="utf-8",
        )

        with patch(
            "check_dependency_anchor.fetch_pypi_metadata",
            return_value={"info": {"requires_dist": None}},
        ):
            result = main(["--requirements", str(req), "--diff", str(diff)])

        assert result == 0

    def test_exact_pin_at_proposed_version_passes(self, tmp_path: Path) -> None:
        """An == pin at the proposed version does not block (proposed not above)."""
        req = tmp_path / "requirements-ci.txt"
        req.write_text(
            textwrap.dedent("""\
                some-anchor==1.0.0
                some-package==1.0.0
            """),
            encoding="utf-8",
        )
        diff = tmp_path / "changes.diff"
        diff.write_text(
            textwrap.dedent("""\
                --- a/requirements-ci.txt
                +++ b/requirements-ci.txt
                @@ -1,2 +1,2 @@
                -some-package==1.0.0
                +some-package==2.0.0
            """),
            encoding="utf-8",
        )

        anchor = _pydantic_metadata(["some-package==2.0.0"])

        with patch(
            "check_dependency_anchor.fetch_pypi_metadata",
            side_effect=lambda pkg, _version: anchor if pkg == "some-anchor" else {},
        ):
            result = main(["--requirements", str(req), "--diff", str(diff)])

        assert result == 0


# ---------------------------------------------------------------------------
# Subprocess integration test (AC1: the script runs as a standalone tool)
# ---------------------------------------------------------------------------


class TestSubprocessIntegration:
    """AC1: the script can be invoked as a subprocess and exits appropriately."""

    def test_script_runs(self) -> None:
        """The script can be invoked as a subprocess and exits 0 with --help."""
        result = subprocess.run(
            [sys.executable, str(_REPO_ROOT / "scripts" / "check_dependency_anchor.py"), "--help"],
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 0
        assert "refuse" in result.stdout.lower()
