"""A/A (negative-control) harness for the aggregation two-arm gate (#163).

Offline, seeded, deterministic. Both arms of each paired run are drawn from the
same Bernoulli(p) process and stopped by the production sequential rule, so any
directional ``two_arm_gate`` call is a false positive by construction.

## What is driven

- ``two_arm_gate`` (``aggregation/two_arm.py``) — the two-arm posterior-difference
  significance gate (DIF K7). Registered constants used here match the existing
  two-arm suite: ``delta=0.1``, ``prob_threshold=0.95``.
- Observation generation mirrors ``ablation/runner.py``: ``BetaBinomialAccumulator``
  + ``check_stop()`` / ``next_check_at()`` with ``N_MIN=8``, ``N_INC=4``,
  ``N_MAX=40``. No fixed-n draws.

``aggregate_skill`` (``engine.py``) is the DB orchestrator over already-stopped
verdicts; it does not own a two-arm significance threshold. The A/A estimand is
the two-arm gate's false-positive rate under identical arms. Engine numerics that
matter for pass/fail (Beta posterior mass) are the same primitives exercised by
the sequential stopper and by ``two_arm_gate``.

## Tolerance arithmetic (N=500, nominal alpha = 1 - prob_threshold = 0.05)

Under a well-calibrated gate the false-positive count ``X`` is modelled as
``X ~ Binomial(N=500, alpha=0.05)``. The acceptance band is the central 95%
probability mass of that binomial (exact, via ``scipy.stats.binom.ppf``):

    lo = binom.ppf(0.025, n=500, p=0.05)   # = 16
    hi = binom.ppf(0.975, n=500, p=0.05)   # = 35
    E[X] = 500 * 0.05 = 25

Assert ``lo <= X <= hi``. This is a Monte-Carlo check that the observed FPR sits
near nominal - not a claim that the Bayesian gate is a frequentist level-alpha
test at every (n, delta). If ``X`` falls outside, do **not** retune thresholds:
file a finding (severity WRONG_NUMBER), xfail with a pointer, record seed + count.

## Sequential-stopping requirement

Each arm is generated by:

    acc = BetaBinomialAccumulator()
    next_at = N_MIN
    while True:
        while acc.n < next_at and acc.n < N_MAX:
            acc.add(Bernoulli(p) in {0.0, 1.0})  # no ties in this harness
        decision = acc.check_stop()
        if decision.should_stop:
            break
        next_at = next_check_at(acc.n)

Stopped ``(w, n)`` for treatment and control feed ``two_arm_gate``. Each arm's
``StoppingReason`` is tallied for the report.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pytest
from scipy.stats import binom  # type: ignore[import-untyped]

from skill_harness.ablation.stopping import (
    N_MAX,
    N_MIN,
    BetaBinomialAccumulator,
    StopDecision,
    StoppingReason,
    next_check_at,
)
from skill_harness.aggregation.two_arm import TwoArmOutcome, two_arm_gate

# ---------------------------------------------------------------------------
# Registered constants (DIF K7 / existing two-arm suite — do not retune)
# ---------------------------------------------------------------------------

N_PAIRS = 500
SEED = 163_2026_08_09  # issue #163, deterministic
NULL_P = 0.5  # identical-arm Bernoulli rate
DELTA = 0.1
PROB_THRESHOLD = 0.95
NOMINAL_ALPHA = 1.0 - PROB_THRESHOLD  # 0.05

# Central 95% band of Binomial(N_PAIRS, NOMINAL_ALPHA) — see module docstring.
FP_COUNT_LO = int(binom.ppf(0.025, N_PAIRS, NOMINAL_ALPHA))
FP_COUNT_HI = int(binom.ppf(0.975, N_PAIRS, NOMINAL_ALPHA))

_REPORT = Path(__file__).resolve().parent.parent / "docs" / "assurance" / "aa-report.md"


# ---------------------------------------------------------------------------
# Offline discipline (pytest-socket)
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def _no_network(socket_disabled: None) -> None:
    """Block all network I/O for every test in this module."""


# ---------------------------------------------------------------------------
# Sequential arm simulation (mirrors ablation/runner.py stop loop)
# ---------------------------------------------------------------------------


def _run_arm_sequential(rng: np.random.Generator, p: float) -> StopDecision:
    """Draw Bernoulli(p) observations through the real sequential stopper."""
    acc = BetaBinomialAccumulator()
    next_at = N_MIN
    decision: StopDecision | None = None
    while acc.n < N_MAX:
        target = min(next_at, N_MAX)
        while acc.n < target:
            obs = 1.0 if float(rng.random()) < p else 0.0
            acc.add(obs)
        decision = acc.check_stop()
        if decision.should_stop:
            return decision
        next_at = next_check_at(acc.n)
        if next_at > N_MAX:
            break
    if decision is None:
        decision = acc.check_stop()
    return decision


@dataclass(frozen=True)
class AAResult:
    """Summary of one full A/A Monte Carlo."""

    n_pairs: int
    false_positive_count: int
    false_positive_rate: float
    outcome_counts: dict[str, int]
    stopping_reason_counts: dict[str, int]
    seed: int
    delta: float
    prob_threshold: float
    nominal_alpha: float
    fp_count_lo: int
    fp_count_hi: int


def run_aa_harness(
    *,
    n_pairs: int = N_PAIRS,
    seed: int = SEED,
    p: float = NULL_P,
    delta: float = DELTA,
    prob_threshold: float = PROB_THRESHOLD,
) -> AAResult:
    """Run ``n_pairs`` identical-arm sequential A/A comparisons."""
    rng = np.random.default_rng(seed)
    outcome_counts: Counter[str] = Counter()
    stopping_reason_counts: Counter[str] = Counter()
    fp = 0

    for _ in range(n_pairs):
        treatment = _run_arm_sequential(rng, p)
        control = _run_arm_sequential(rng, p)

        for arm in (treatment, control):
            reason = arm.stopping_reason
            assert reason is not None
            stopping_reason_counts[reason.value] += 1

        # Binary observations => w is integer-valued; cast for the int API.
        t_pass = int(treatment.w_accumulator)
        c_pass = int(control.w_accumulator)
        t_n = treatment.n_samples
        c_n = control.n_samples
        assert t_n >= 1 and c_n >= 1
        assert 0 <= t_pass <= t_n and 0 <= c_pass <= c_n

        gate = two_arm_gate(
            t_pass,
            t_n,
            c_pass,
            c_n,
            delta=delta,
            prob_threshold=prob_threshold,
        )
        outcome_counts[gate.outcome.value] += 1
        if gate.outcome is not TwoArmOutcome.NULL:
            fp += 1

    return AAResult(
        n_pairs=n_pairs,
        false_positive_count=fp,
        false_positive_rate=fp / n_pairs,
        outcome_counts=dict(outcome_counts),
        stopping_reason_counts=dict(stopping_reason_counts),
        seed=seed,
        delta=delta,
        prob_threshold=prob_threshold,
        nominal_alpha=1.0 - prob_threshold,
        fp_count_lo=int(binom.ppf(0.025, n_pairs, 1.0 - prob_threshold)),
        fp_count_hi=int(binom.ppf(0.975, n_pairs, 1.0 - prob_threshold)),
    )


# ---------------------------------------------------------------------------
# Tolerance constants pin
# ---------------------------------------------------------------------------


def test_binomial_tolerance_constants() -> None:
    """Documented lo/hi match exact Binomial(500, 0.05) central 95% mass."""
    assert pytest.approx(0.05) == NOMINAL_ALPHA
    assert FP_COUNT_LO == 16
    assert FP_COUNT_HI == 35
    assert int(binom.ppf(0.025, N_PAIRS, NOMINAL_ALPHA)) == FP_COUNT_LO
    assert int(binom.ppf(0.975, N_PAIRS, NOMINAL_ALPHA)) == FP_COUNT_HI


# ---------------------------------------------------------------------------
# Core A/A harness
# ---------------------------------------------------------------------------


def test_aa_false_positive_rate_within_binomial_tolerance() -> None:
    """N=500 identical-arm sequential runs: FPR inside Binomial(500, 0.05) band.

    Tolerance arithmetic (see module docstring)::

        alpha = 1 - prob_threshold = 0.05
        lo = binom.ppf(0.025, 500, 0.05) = 16
        hi = binom.ppf(0.975, 500, 0.05) = 35
        assert lo <= false_positive_count <= hi

    Outside the band -> WRONG_NUMBER finding + xfail; never retune thresholds.
    """
    result = run_aa_harness()

    assert result.n_pairs == N_PAIRS
    assert result.seed == SEED
    assert sum(result.outcome_counts.values()) == N_PAIRS
    # Two arms per pair.
    assert sum(result.stopping_reason_counts.values()) == 2 * N_PAIRS
    # Only production StoppingReason values.
    assert set(result.stopping_reason_counts).issubset({r.value for r in StoppingReason})

    fp = result.false_positive_count
    assert FP_COUNT_LO <= fp <= FP_COUNT_HI, (
        f"A/A false-positive count {fp} outside binomial tolerance "
        f"[{FP_COUNT_LO}, {FP_COUNT_HI}] for Binomial({N_PAIRS}, {NOMINAL_ALPHA}). "
        f"rate={result.false_positive_rate:.4f}; seed={SEED}. "
        "Do not retune thresholds — file docs/findings with severity WRONG_NUMBER."
    )


def test_aa_harness_is_deterministic() -> None:
    """Same seed yields bit-identical counts (no network, no wall clock)."""
    a = run_aa_harness()
    b = run_aa_harness()
    assert a == b


def test_aa_report_records_rate_and_tolerance() -> None:
    """docs/assurance/aa-report.md records measured rate + tolerance arithmetic."""
    assert _REPORT.is_file(), f"missing A/A report at {_REPORT}"
    text = _REPORT.read_text(encoding="utf-8")
    assert "false-positive" in text.lower() or "false positive" in text.lower()
    assert "0.05" in text or "5%" in text
    assert "binom" in text.lower() or "Binomial" in text
    assert "500" in text
    assert "StoppingReason" in text or "stopping_reason" in text
    assert str(SEED) in text or "163_2026_08_09" in text
    # Measured count from the seeded harness must appear.
    result = run_aa_harness()
    assert str(result.false_positive_count) in text
    for reason in result.stopping_reason_counts:
        assert reason in text
