#!/usr/bin/env python3
"""Run mutmut against one measurement-path module with scoped tests (#166).

Usage:
  python scripts/run_mutation.py aggregation
  python scripts/run_mutation.py ablation
  python scripts/run_mutation.py extractor
  python scripts/run_mutation.py audit
  python scripts/run_mutation.py aggregation --only-mutate src/skill_harness/aggregation/two_arm.py

Writes setup.cfg (gitignored) for the chosen module, then invokes `mutmut run`.
Results live under mutants/ and are summarized by `mutmut results`.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Per-module mutate globs and pytest selection. Scoped deliberately: Monte Carlo
# assurance harnesses (AA #163, calibration #164) are multi-minute and kill via
# statistical mass, not unit branches — excluded from mutmut selection; they
# remain in the full suite. Differential (#165) is included for aggregation
# numerics.
MODULES: dict[str, dict[str, list[str]]] = {
    "aggregation": {
        "only_mutate": [
            "src/skill_harness/aggregation/*.py",
        ],
        "tests": [
            "tests/test_aggregation_engine.py",
            "tests/test_aggregation_fit.py",
            "tests/test_aggregation_status.py",
            "tests/test_aggregation_verdict.py",
            "tests/test_aggregation_report.py",
            "tests/test_aggregation_profile_anti_fusion.py",
            "tests/test_aggregation_profile_mappers.py",
            "tests/test_two_arm_gate.py",
            "tests/test_value_class_registry.py",
            "tests/test_matched_effect.py",
            "tests/test_aggregation_differential.py",
            "tests/test_aggregation_mutation.py",
        ],
    },
    "ablation": {
        "only_mutate": [
            "src/skill_harness/ablation/*.py",
        ],
        "tests": [
            "tests/ablation/",
            "tests/test_ablation_sizing.py",
            "tests/test_ablation_report_verdict_id.py",
            "tests/test_aggregation_mutation.py",
            "tests/test_ablation_mutation.py",
        ],
    },
    "extractor": {
        "only_mutate": [
            "src/skill_harness/extractor/*.py",
        ],
        "tests": [
            "tests/extractor/",
            "tests/test_corpus_census.py",
            "tests/test_corpus_coverage.py",
            "tests/test_clause_evidence_audit.py",
            "tests/test_extractor_mutation.py",
        ],
    },
    "audit": {
        "only_mutate": [
            "src/skill_harness/audit/*.py",
        ],
        "tests": [
            # Direct importers of skill_harness.audit (A29 raw oracle surface).
            "tests/test_repo_roundtrip.py",
            "tests/test_admissibility_write_time_snapshot.py",
            "tests/test_dual_write_partial.py",
            "tests/test_skill_audit.py",
            "tests/test_audit_metric.py",
            "tests/test_clause_evidence_audit.py",
            "tests/test_audit_mutation.py",
        ],
    },
}

SETUP_CFG_TEMPLATE = textwrap.dedent(
    """\
    [mutmut]
    # Generated by scripts/run_mutation.py — do not hand-edit; regenerated per run.
    # mutmut==3.7.0 (requirements-assurance-container.txt)
    source_paths =
        src/skill_harness
    only_mutate =
    {only_mutate}
    do_not_mutate =
    {do_not_mutate}
    also_copy =
        docs/
        examples/
        assets/
        scripts/
        requirements-ci.txt
        requirements-assurance-container.txt
        README.md
        LICENSE
        CHANGELOG.md
        pyrightconfig.json
    pytest_add_cli_args_test_selection =
    {tests}
    pytest_add_cli_args =
        -m
        not live and not slow
    timeout_multiplier = 15
    timeout_constant = 2
    use_git_change_detection = false
    debug = false
    """
)


def write_setup_cfg(module: str, only_mutate_override: list[str] | None) -> Path:
    spec = MODULES[module]
    only = only_mutate_override if only_mutate_override else spec["only_mutate"]
    # Drop test paths that do not exist yet (mutation killer modules land later).
    tests = [t for t in spec["tests"] if (ROOT / t).exists() or t.endswith("/")]
    # audit/ is only __init__.py (A29 raw-oracle surface) — must mutate it.
    # mutmut rejects empty do_not_mutate entries; use a never-matching path.
    if module == "audit":
        do_not = "    __never_match_audit_init_must_mutate__/**"
    else:
        do_not = "    **/__init__.py"
    body = SETUP_CFG_TEMPLATE.format(
        only_mutate="\n".join(f"    {p}" for p in only),
        do_not_mutate=do_not,
        tests="\n".join(f"    {t}" for t in tests),
    )
    path = ROOT / "setup.cfg"
    path.write_text(body, encoding="utf-8")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("module", choices=sorted(MODULES))
    parser.add_argument(
        "--only-mutate",
        action="append",
        default=None,
        help="Override only_mutate glob (repeatable).",
    )
    parser.add_argument(
        "mutmut_args",
        nargs="*",
        help="Extra args forwarded to `mutmut run` (e.g. survivor names).",
    )
    args = parser.parse_args()
    cfg = write_setup_cfg(args.module, args.only_mutate)
    print(f"wrote {cfg} for module={args.module}", flush=True)
    print(cfg.read_text(encoding="utf-8"), flush=True)
    cmd = [sys.executable, "-m", "mutmut", "run", *args.mutmut_args]
    print("+", " ".join(cmd), flush=True)
    return subprocess.call(cmd, cwd=ROOT)  # noqa: S603


if __name__ == "__main__":
    raise SystemExit(main())
